name: codecove

on: [push]

jobs:
  steps:
  - uses: actions/checkout@main
  - uses: codecov/codecov-action@v5
    with:
      fail_ci_if_error: true # optional (default = false)
      files: ./coverage1.xml,./coverage2.xml # optional
      flags: unittests # optional
      name: codecov-umbrella # optional
      verbose: true # optional (default = false)
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}