name: codecov

on: [push]

jobs:
  test_and_upload_coverage:
    name: "Coverage on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      OS: ${{ matrix.os }}
      PYTHON: "3.10"
      DJANGO_SETTINGS_MODULE: xuitter.settings

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and generate coverage
        working-directory: ./xuitter-backend
        run: |
          coverage run manage.py test
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
          files: ./xuitter-backend/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
