name: codecov

on: [push]

jobs:
  test_and_upload_coverage:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate coverage
      working-directory: ./xuitter-backend
      env:
        DJANGO_SETTINGS_MODULE: xuitter.settings
      run: |
        coverage run manage.py test
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        flags: unittests
        name: codecov-umbrella
        verbose: true
        files: ./xuitter-backend/coverage.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        